class AppStrings {
  static const String createdBy = 'Created by';
  static const String creatorName = 'SofTonik';
  static const String homeTitle = 'Home';
  static const String splashLottieAsset = 'assets/animations/books.json';
  static const String clientBook = 'Client Book';
  static const String businessBook = 'Business Book';
  static const String stockBook = 'Stock Book';
  static const String expenseBook = 'Expense Book';

  // Client related strings
  static const String addClient = 'Add Client';
  static const String editClient = 'Edit Client';
  static const String updateClient = 'Update Client';
  static const String clientName = 'Client Name';
  static const String mobileNumber = 'Mobile Number';
  static const String businessType = 'Business Type';
  static const String addClientSuccess = 'Client added successfully!';
  static const String updateClientSuccess = 'Client updated successfully!';

  // Form validation messages
  static const String pleaseEnterClientName = 'Please enter client name';
  static const String nameMinLength = 'Name must be at least 2 characters';
  static const String pleaseEnterMobileNumber = 'Please enter mobile number';
  static const String mobileMinLength =
      'Mobile number must be at least 10 digits';
  static const String pleaseEnterBusinessType = 'Please enter business type';

  // Transaction related strings
  static const String totalReceived = 'TOTAL\nRECEIVED';
  static const String totalPaid = 'TOTAL\nPAID';
  static const String youWillGet = 'YOU WILL\nGet';
  static const String paid = 'PAID';
  static const String received = 'RECEIVED';
  static const String dateAndTime = 'Date & Time';
  static const String receivedColumn = 'Received';
  static const String paidColumn = 'Paid';
  static const String addTransaction = 'Add Transaction';
  static const String transactionType = 'Transaction Type';
  static const String amount = 'Amount';
  static const String date = 'Date';
  static const String note = 'Note (Optional)';
  static const String enterAmount = 'Please enter amount';
  static const String validAmount = 'Please enter a valid amount';
  static const String amountGreaterThanZero = 'Amount must be greater than 0';
  static const String transactionAddedSuccess =
      'Transaction added successfully!';
  static const String failedToAddTransaction = 'Failed to add transaction: ';

  // Error messages
  static const String errorPrefix = 'Error: ';

  // Delete confirmation strings
  static const String deleteConfirmation = 'Delete Confirmation';
  static const String enterClientId = 'Enter Client ID';
  static const String clientId = 'Client ID';
  static const String pleaseEnterClientId = 'Please enter client ID';
  static const String confirmDelete =
      'Are you sure you want to delete this client? (Y/N)';
  static const String deleteSuccess = 'Client deleted successfully!';
  static const String deleteFailed = 'Failed to delete client: ';
  static const String clientNotFound = 'Client not found with the given ID';
  static const String yes = 'Yes';
  static const String no = 'No';
  static const String cancel = 'Cancel';
  static const String searchClient = 'Search Client';

  // Enhanced delete confirmation page strings
  static const String searchClientByCriteria =
      'Search Client by Name, Mobile, or ID';
  static const String searchClientHint = 'Type to search clients...';
  static const String clientSelected = 'Selected: ';
  static const String pleaseSelectClientToDelete =
      'Please select a client to delete';
  static const String errorLoadingClientsForDelete = 'Error loading clients: ';
  static const String errorSearchingClient = 'Error searching client: ';
  static const String clientFound = 'Client found: ';
  static const String totalClients = 'Total Clients: ';
  static const String deleteClientFinalConfirmation =
      'Are you absolutely sure you want to delete ';
  static const String deleteClientFinalWarning =
      '? This action cannot be undone.';
  static const String deleteActionCannotBeUndone =
      '⚠️ This action cannot be undone!';

  // PDF related strings
  static const String clientNameCannotBeEmpty = 'Client name cannot be empty';
  static const String clientIdCannotBeEmpty = 'Client ID cannot be empty';
  static const String invalidReceivedAmount =
      'Invalid received amount in transaction';
  static const String invalidPaidAmount = 'Invalid paid amount in transaction';
  static const String appName = 'ApniBook';
  static const String transactionReport = 'Transaction Report';
  static const String clientInformation = 'Client Information';
  static const String transactionSummary = 'Transaction Summary';
  static const String transactionHistory = 'Transaction History';
  static const String noTransactionsFound = 'No transactions found';
  static const String generatedByApp = 'Generated by ApniBook App';
  static const String generatedOn = 'Generated on: ';
  static const String nameLabel = 'Name: ';
  static const String idLabel = 'ID: ';
  static const String totalReceivedLabel = 'Total Received:';
  static const String totalPaidLabel = 'Total Paid:';
  static const String balanceLabel = 'Balance:';
  static const String dateAndTimeColumn = 'Date & Time';
  static const String shareText = 'Transaction report for ';
  static const String shareSubject = 'ApniBook Transaction Report - ';

  // Exit confirmation strings
  static const String exitApp = 'Exit App';
  static const String exitConfirmationMessage =
      'Are you sure you want to exit the app?\n\nPress back again quickly to exit without confirmation.';

  // Client details page strings
  static const String noTransactionsYet = 'No transactions yet';
  static const String addFirstTransactionMessage =
      'Add your first transaction using the + button';
  static const String errorLoadingTransactions = 'Error loading transactions';
  static const String retry = 'Retry';
  static const String noTransactionsToExport = 'No transactions to export';
  static const String pleaseWaitForTransactions =
      'Please wait for transactions to load';
  static const String noTransactionDataAvailable =
      'No transaction data available';
  static const String errorGeneratingPdf = 'Error generating PDF: ';
  static const String pdfGeneratedSuccessfully = 'PDF Generated Successfully!';
  static const String fileSavedTo = 'File saved to: ';
  static const String whatWouldYouLikeToDo = 'What would you like to do?';
  static const String pdfSavedToDevice = 'PDF saved to device';
  static const String ok = 'OK';
  static const String share = 'Share';
  static const String errorSharingPdf = 'Error sharing PDF: ';
  static const String am = 'AM';
  static const String pm = 'PM';

  // Client list page strings
  static const String searchClients = 'Search clients...';
  static const String noClientsFound = 'No clients found';
  static const String addFirstClientMessage =
      'Add your first client using the + button';
  static const String errorLoadingClients = 'Error loading clients';
  static const String deleteClient = 'Delete Client';
  static const String deleteClientConfirmation =
      'Are you sure you want to delete ';
  static const String deleteClientWarning = '? This action cannot be undone.';
  static const String delete = 'Delete';

  // Dashboard page strings
  static const String menu = 'Menu';
  static const String help = 'Help';

  // Stock list page strings
  static const String noStockItems = 'No stock items. Tap + to add.';

  // Add/Edit stock page strings
  static const String addStock = 'Add Stock';
  static const String editStock = 'Edit Stock';
  static const String updateStock = 'Update Stock';
  static const String productName = 'Product Name';
  static const String pleaseEnterProductName = 'Please enter product name';
  static const String quantity = 'Quantity';
  static const String pleaseEnterQuantity = 'Please enter quantity';
  static const String pleaseEnterValidQuantity =
      'Please enter a valid quantity';
  static const String pricePerUnit = 'Price Per Unit (₹)';
  static const String pleaseEnterPricePerUnit = 'Please enter price per unit';
  static const String pleaseEnterValidPrice = 'Please enter a valid price';
}
